Repository bdx-iot/meta-stm32mp1, pull requests merged in 2020-02, with the labels that each got.

#34 u-boot: use u-boot version in openembedded-core
  classes/stm32mp1.bbclass
  conf/machine/include/stm32mp1.inc
  conf/machine/stm32mp157a-dk1.conf
  recipes-bsp/u-boot/u-boot-mainline/0002-stm32mp1-Enable-redundant-environment.patch
  recipes-bsp/u-boot/u-boot-mainline_2019.10.bb
  recipes-bsp/u-boot/u-boot-mainline_git.bb
  recipes-bsp/u-boot/u-boot-stm-common.inc
  recipes-bsp/u-boot/u-boot/0001-stm32mp1-Disable-ADC.patch
  recipes-bsp/u-boot/u-boot/0002-stm32mp1-Replace-ENV_IS_EXT4-to-MMC.patch
  recipes-bsp/u-boot/u-boot_2020.01.bbappend
Labels: U-Boot

#35 ci: add 'upload-artifact' step
  .github/workflows/kas.yml
Labels: CI

#36 wic: rename U-Boot partition from 'uboot' to 'ssbl'
  wic/stm32mp1.wks
Labels: U-Boot, enhancement
